### ISSUE TITLE
RTC and GEOS?

### ISSUE THREAD

**Issue by sy2002** [Kugelblitz360/C64MEGA65DOCS#9]
Sorry, if I missed the obvious - just scrolled quickly through the doc on a headline level: Do we have any RTC and GEOS info in the documentation. The content from here:

https://github.com/MJoergen/C64MEGA65/blob/master/doc/RTC.md

**Comment by sy2002** [comment]
In future (2025, planned release V5.3) some things might change (see this comment: https://github.com/MJoergen/C64MEGA65/issues/164#issuecomment-2466848607) - but for now, as of V5.1 and the planned V5.2, this content is 100% valid.

**Comment by Kugelblitz360** [comment]
Yes, it's in the FAQ here: https://c64.mega65.org/C64MEGA65DOCS/faq-and-other-stuff.html#other-hardware-issues and here: https://kugelblitz360.github.io/C64MEGA65DOCS/faq-and-other-stuff.html#hacks-tips-and-tricks

If you think it needs better visibility I would restructure and am open for suggestions.

**Comment by sy2002** [comment]
@Kugelblitz360 I propose to reopen this one (I can't due to missing user rights) - and to have a short chapter called GEOS which shares some of the GEOS related insights (from AmokPhaze's PDF), links to some of the mouse how-to's and which includes infos about the Real Time Clock (currently the documentation is only linking to RTC.md in the old documentation).

We might also share some tips how to use GEOS best using the REU:  Have a virtual drive, copy important files there and have a lightning fast GEOS then, ...  (Not sure if this is described in AmokPhaze's PDF).

**Comment by Kugelblitz360** [comment]
OK, besides giving Geos better visibility I need to look at the RTC. The trouble is that this is one of the worst documented bits of extra hardware for the C64 - at least standard internet searches really do not give a lot of info about this specific RTC. Thinking of enabling a SEARCH function on the docs, need to experiment with that because it adds another plugin.
Do you also want to do stuff on C64OS? Does anybody of the team have a license?
________________________________

**Comment by sy2002** [comment]
Indeed, C64OS would be a cool idea, too. Then the big headline would not be GEOS but more something like Operating Systems and then sub chapters for C64OS and GEOS. Unfortunately I do not have a license but maybe you want to ask the community on Forum64 or Discord.
